DROP TABLE IF EXISTS Reviews;
DROP TABLE IF EXISTS Review_Meta_Data;
DROP TABLE IF EXISTS Characteristics;
DROP TABLE IF EXISTS Review_Photos;
DROP TABLE IF EXISTS Ratings;
DROP TABLE IF EXISTS Recommend;
DROP TABLE IF EXISTS Fit;
DROP TABLE IF EXISTS Quality;
DROP TABLE IF EXISTS Length;
DROP TABLE IF EXISTS Comfort;

CREATE TABLE Reviews (
  id SERIAL PRIMARY KEY,
  product_id INTEGER NOT NULL DEFAULT NULL,
  rating INTEGER NOT NULL DEFAULT NULL,
  summary VARCHAR(1000) NOT NULL DEFAULT '',
  recommend bit NOT NULL DEFAULT '0',
  response NULL,
  body VARCHAR(1000) NOT NULL DEFAULT '',
  date_created BIGINT NOT NULL,
  reviewer_name VARCHAR(50) NOT NULL DEFAULT '',
  helpfulness INTEGER NULL DEFAULT '0',

);

CREATE TABLE Review_Photos (
  id SERIAL PRIMARY KEY,
  review_id INTEGER,
  url VARCHAR(1000)
);

CREATE TABLE Review_Meta_Data (
  id SERIAL PRIMARY KEY,
  product_id INTEGER NOT NULL DEFAULT NULL,

);

CREATE TABLE Ratings (
  id SERIAL PRIMARY KEY,
  product_id INTEGER NOT NULL DEFAULT NULL,
  rating_1 INTEGER NULL DEFAULT '0',
  rating_2 INTEGER NULL DEFAULT '0',
  rating_3 INTEGER NULL DEFAULT '0',
  rating_4 INTEGER NULL DEFAULT '0',
  rating_5 INTEGER NULL DEFAULT '0',
);

CREATE TABLE Recommend (
  id SERIAL PRIMARY KEY,
  product_id INTEGER NOT NULL DEFAULT NULL,
  recommend_true INTEGER NULL DEFAULT '0',
  recommend_false INTEGER NULL DEFAULT '0',
)

CREATE TABLE Characteristics; (
  id SERIAL PRIMARY KEY,
  product_id INTEGER NOT NULL DEFAULT NULL,
  characteristic_name VARCHAR(20) NOT NULL DEFAULT '',
);

CREATE TABLE Fit (
  id SERIAL PRIMARY KEY,
  characteristics_id INTEGER NOT NULL DEFAULT NULL,
  fit_value INTEGER NULL DEFAULT '0',
);

CREATE TABLE Quality (
  id SERIAL PRIMARY KEY,
  characteristics_id INTEGER NOT NULL DEFAULT NULL,
  quality_value INTEGER NULL DEFAULT '0',
);

CREATE TABLE Length (
  id SERIAL PRIMARY KEY,
  characteristics_id INTEGER NOT NULL DEFAULT NULL,
  length_value INTEGER NULL DEFAULT '0',
);

CREATE TABLE Comfort (
  id SERIAL PRIMARY KEY,
  characteristics_id INTEGER NOT NULL DEFAULT NULL,
  comfort_value INTEGER NULL DEFAULT '0',
);